<style>
  .row {
    margin-bottom: 10px;
  }

  .align-center {
    display: flex;
    align-items: center;
  }

  label[for="nrCep"] {
    display: inline-flex;
  }

  label[for="nrCep"] svg {
    height: 25px;
    width: 25px;
    margin: none;
    padding-left: 10px;
    background: rgb(255, 255, 255);
    display: block;
    shape-rendering: auto;
  }
</style>

<div class="row">
  <div class="col-2">
    <label for="dsTipoPessoa" class="form-label">Tipo de cliente</label>
    <select class="form-select" aria-label="Default select example" id="dsTipoPessoa" name="dsTipoPessoa" onchange="changeTipoPessoa(this.value)" required>
      <option selected>Selecione o tipo de pessoa</option>
      <option value="PF">Pessoa física</option>
      <option value="PJ">Pessoa jurídica</option>
      <option value="O">Outros</option>
    </select>
  </div>
  <div class="col-2">
    <label for="nrCpfCnpj" class="form-label">CPF/CNPJ</label>
    <input type="text" class="form-control" id="nrCpfCnpj" name="nrCpfCnpj" oninput="this.value = maskCpfCnpj(this.value)" required>
  </div>
  <div class="col-1">
    <label for="cdRegistro" class="form-label">Código</label>
    <input type="text" class="form-control" id="cdRegistro" name="cdRegistro" required>
  </div>
  <div class="col-2">
    <label for="nrInscricaoEst" class="form-label">Inscrição estadual</label>
    <input type="text" class="form-control" id="nrInscricaoEst" name="nrInscricaoEst" required>
  </div>
  <div class="col-1 d-flex align-items-center">
    <label class="form-check-label" for="ieIsentoInsEst">
      <input type="checkbox" class="form-check-input" id="ieIsentoInsEst" name="ieIsentoInsEst" onchange="changeIsento(this.checked)" >
      Isento
    </label>
  </div>
  <div class="col-2">
    <label for="nrInscricaoMun" class="form-label">Inscrição municipal</label>
    <input type="text" class="form-control" id="nrInscricaoMun" name="nrInscricaoMun" required>
  </div>
  <div class="col-2">
    <label for="nrInscricaoSuframa" class="form-label">Inscrição suframa</label>
    <input type="text" class="form-control" id="nrInscricaoSuframa" name="nrInscricaoSuframa" required>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <label for="nmCliente" class="form-label">Nome</label>
    <input type="text" class="form-control" id="nmCliente" name="nmCliente" required>
  </div>
</div>
<div class="row">
  <div class="col-6">
    <label for="dsNomeFantasia" class="form-label">Nome fantasia</label>
    <input type="text" class="form-control" id="dsNomeFantasia" name="dsNomeFantasia" required>
  </div>
  <div class="col-6">
    <label for="dsRazaoSocial" class="form-label">Razão social</label>
    <input type="text" class="form-control" id="dsRazaoSocial" name="dsRazaoSocial" required>
  </div>
</div>
<div class="row">
  <div class="col-2">
    <label for="nrCep" class="form-label">
      CEP
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: none;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <circle cx="50" cy="50" fill="none" stroke="#2e2e2e" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
          <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ -->
      </svg>
    </label>
    <input type="text" class="form-control" id="nrCep" name="nrCep" onblur="consultaCepOnBlur(this)" onkeydown="if (event.key === 9) {consultaCepOnBlur(this)}" oninput="this.value = maskCep(this.value)" required>
  </div>
  <div class="col-5">
    <label for="dsEndereco" class="form-label">Endereço</label>
    <input type="text" class="form-control" id="dsEndereco" name="dsEndereco" required>
  </div>
  <div class="col-1">
    <label for="nrEndereco" class="form-label">Número</label>
    <input type="text" class="form-control" id="nrEndereco" name="nrEndereco" required>
  </div>
  <div class="col-4">
    <label for="dsComplemento" class="form-label">Complemento</label>
    <input type="text" class="form-control" id="dsComplemento" name="dsComplemento">
  </div>
</div>
<div class="row">
  <div class="col-3">
    <label for="nmBairro" class="form-label">Bairro</label>
    <input type="text" class="form-control" id="nmBairro" name="nmBairro" required>
  </div>
  <div class="col-3">
    <label for="nmMunicipio" class="form-label">Município</label>
    <input type="text" class="form-control" id="nmMunicipio" name="nmMunicipio" required>
  </div>
  <div class="col-3">
    <label for="nmEstado" class="form-label">Estado</label>
    <input type="text" class="form-control" id="nmEstado" name="nmEstado" required>
  </div>
  <div class="col-3">
    <label for="nmPais" class="form-label">País</label>
    <input type="text" class="form-control" id="nmPais" name="nmPais" required>
  </div>
</div>

<script>
  const maskCpfCnpj = (value) => {
    const tipoCliente = document.querySelector('#dsTipoPessoa').value;
    if (tipoCliente === 'PJ') {
      return value
        .replace(/\D/g, '')
        .replace(/(\d{2})(\d)/, '$1.$2')
        .replace(/(\d{3})(\d)/, '$1.$2')
        .replace(/(\d{3})(\d)/, '$1/$2')
        .replace(/(\d{4})(\d)/, '$1-$2')
        .replace(/(-\d{2})\d+?$/, '$1');
    } else if (tipoCliente === 'PF') {
      return value
        .replace(/\D/g, '')
        .replace(/(\d{3})(\d)/, '$1.$2')
        .replace(/(\d{3})(\d)/, '$1.$2')
        .replace(/(\d{3})(\d)/, '$1-$2')
        .replace(/(-\d{2})\d+?$/, '$1');
    } else {
      return value;
    }
  }

  const maskCep = (value) => {
    return value
      .replace(/\D/g, '')
      .replace(/(\d{5})(\d)/, '$1-$2')
      .replace(/(-\d{3})\d+?$/, '$1');
  }

  function changeTipoPessoa(tipoCliente) {
    const nome = document.querySelector('#nmCliente');
    const nomeFantasia = document.querySelector('#dsNomeFantasia');
    const razaoSocial = document.querySelector('#dsRazaoSocial');
    const nomeRow = document.querySelector('#nmCliente').parentElement.parentElement;
    const pjNomesRow = document.querySelector('#dsNomeFantasia').parentElement.parentElement;
    if (tipoCliente === 'PF') {
      nomeFantasia.disabled = true;
      razaoSocial.disabled = true;
      pjNomesRow.style.display = 'none';
      nome.disabled = false;
      nomeRow.style.display = '';
    } else if (tipoCliente === 'PJ') {
      nomeFantasia.disabled = false;
      razaoSocial.disabled = false;
      pjNomesRow.style.display = '';
      nome.disabled = true;
      nomeRow.style.display = 'none';
    } else {
      nomeFantasia.disabled = false;
      razaoSocial.disabled = false;
      pjNomesRow.style.display = '';
      nome.disabled = false;
      nomeRow.style.display = '';
    }
    document.querySelector('#nrCpfCnpj').value = maskCpfCnpj(document.querySelector('#nrCpfCnpj').value);
  }

  function changeIsento(isento) {
    const inscricaoEstadual = document.querySelector('#nrInscricaoEst');
    if (isento) {
      inscricaoEstadual.disabled = true;
    } else {
      inscricaoEstadual.disabled = false;
    }
  }

  function consultaCepOnBlur(input) {
    const cep = input.value.replace(/\D/g, '');
    if (cep.length !== 8) return;
    const url = `https://viacep.com.br/ws/${cep}/json/`;
    document.querySelector('label[for="nrCep"] svg').style.display = 'block';
    fetch(url)
      .then(response => response.json())
      .then(data => {
        document.querySelector('#dsEndereco').value = data.logradouro ?? '';
        document.querySelector('#nmBairro').value = data.bairro ?? '';
        document.querySelector('#nmMunicipio').value = data.localidade ?? '';
        document.querySelector('#nmEstado').value = data.uf ?? '';
        document.querySelector('#nmPais').value = 'Brasil';
        document.querySelector('label[for="nrCep"] svg').style.display = 'none';
      })
      .catch(error => console.error(error));
  }

  function validateRules(event) {
    if (document.querySelector('#ieIsentoInsEst').checked) {
      document.querySelector('#nrInscricaoEst').value = '';
    }
    if (document.querySelector('#dsTipoPessoa').value === 'PF') {
      document.querySelector('#dsNomeFantasia').value = '';
      document.querySelector('#dsRazaoSocial').value = '';
    } else if (document.querySelector('#dsTipoPessoa').value === 'PJ') {
      document.querySelector('#nmCliente').value = '';
    }
    document.querySelector('#nrCpfCnpj').value =
      document.querySelector('#nrCpfCnpj').value.replace(/\D/g, '');
  }

  function fillForm(data) {
    document.querySelector('#dsTipoPessoa').value = data.dsTipoPessoa;
    document.querySelector('#nrCpfCnpj').value = data.nrCpfCnpj;
    document.querySelector('#cdRegistro').value = data.cdRegistro;
    document.querySelector('#nmCliente').value = data.nmCliente;
    document.querySelector('#dsNomeFantasia').value = data.dsNomeFantasia;
    document.querySelector('#dsRazaoSocial').value = data.dsRazaoSocial;
    document.querySelector('#ieIsentoInsEst').checked = data.ieIsentoInsEst;
    document.querySelector('#nrInscricaoEst').value = data.nrInscricaoEst;
    document.querySelector('#nrInscricaoMun').value = data.nrInscricaoMun;
    document.querySelector('#nrInscricaoSuframa').value = data.nrInscricaoSuframa;
    document.querySelector('#nrCep').value = data.nrCep;
    document.querySelector('#dsEndereco').value = data.dsEndereco;
    document.querySelector('#nrEndereco').value = data.nrEndereco;
    document.querySelector('#dsComplemento').value = data.dsComplemento;
    document.querySelector('#nmBairro').value = data.nmBairro;
    document.querySelector('#nmMunicipio').value = data.nmMunicipio;
    document.querySelector('#nmEstado').value = data.nmEstado;
    document.querySelector('#nmPais').value = data.nmPais;
  }

  <?php
  if (isset($_SESSION['cliente'])) {
    $cliente = $_SESSION['cliente'];
    unset($_SESSION['cliente']);
  ?>
    const cliente = <?= json_encode($cliente) ?>;
    fillForm(cliente);
    changeTipoPessoa(cliente.dsTipoPessoa);
    changeIsento(cliente.ieIsentoInsEst);
    document.querySelector('#nrCpfCnpj').value = maskCpfCnpj(cliente.nrCpfCnpj);
  <?php } ?>
</script>
